#:schema https://json.schemastore.org/pyproject.json

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 61.0"]

[project]
authors = [{ name = "Phi-Long Le", email = "philong6297.play@gmail.com" }]
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Topic :: Software Development :: Build Tools",
  "Topic :: Utilities",
]
dependencies = ["gitpython>=3.1", "pathspec>=0.12", "pydantic>=2.10"]
description = "A tool to manage patches for submodules in Chromium-based project."
keywords = ["chromium", "patches", "submodules"]
license = "MIT"
name = "crpatcher"
readme = "README.md"
requires-python = ">=3.11"
version = "0.1.0"

[dependency-groups]
dev = ["ruff>=0.10.0"]
test = [
  "coverage>=7.8",
  "decopatch>=1.4",
  "pytest-cases>=3.8",
  "pytest-cov>=4.2",
  "pytest>=8",
]

[project.urls]
Homepage = "https://github.com/philong6297/crpatcher"

[tool.uv]
default-groups = ["dev", "test"]

[tool.setuptools]
package-dir = { "" = "src" }
packages = ["crpatcher"]

[tool.ruff.format]
line-ending = "lf"

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]
required_plugins = ["pytest-cases>=3.8"]
testpaths = ["tests"]
tmp_path_retention_policy = "failed"
verbosity_assertions = 2
verbosity_test_cases = 2

[tool.pyright]
include = ["src/crpatcher", "tests"]
strict = ["src/crpatcher"]
